version: "3"
volumes:
  pgdata:
services:
  db:
    image: postgres:12-alpine
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=hello
      - POSTGRES_DB=hello

  api:
    image: openjdk:13
    volumes:
    - .:/app
    working_dir: /app
    ports:
     - 8080:8080
    command: ./gradlew run


